name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Check secrets (for debugging, ensure these steps do not expose sensitive data)
      run: |
        echo "DOCKER_USERNAME is set: ${{ secrets.DOCKER_USERNAME != '' }}"
        echo "DOCKER_PASSWORD is set: ${{ secrets.DOCKER_PASSWORD != '' }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/forum-fr:latest

    - name: Log out of Docker Hub
      if: always()
      run: docker logout